init:
  - git config --global core.autocrlf input
install:
  - git submodule update --init --recursive
before_build:
  - cmd: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\gacutil.exe' /i "lib\FS\FSharp.Core.dll"
  - cmd: msiexec.exe /i "lib\Pex\pex.academic.x86.msi" /quiet /norestart
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
